version: "3"
services:
  api:
    build:
      context: ./src/server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  frontend:
    build:
      context: ./src/client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api