import type { Metadata } from "next";
import {inter,lusitana,josefin, roboto, fira} from "./ui/font"
import "./ui/globals.css";
import Navbar from "../components/Fragments/navbar"

export const metadata: Metadata = {
  title: "WikiRace by StressRace",
  description: "Generated by StressRace",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <Navbar />
        {children}
        </body>
    </html>
  );
}
